# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ action ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
       python-version: '3.6'  
   
    - name: set ndk
      run: echo "::set-env name=ANDROID_NDK_ROOT::$ANDROID_SDK_ROOT/ndk-bundle"

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-multilib lib32stdc++-5-dev flex bison

    # Runs a set of commands using the runners shell
    - name: build
      run: |
       git clone --recurse-submodules https://github.com/frida/frida && cd frida && make build/frida-android-arm/lib/pkgconfig/frida-core-1.0.pc

    - name: check
      run: |
        file frida/build/frida-android-arm/bin/frida-server
        file frida/build/frida-android-arm64/bin/frida-server
    
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: frida-server-arm-arm64
        path: frida/build/**/frida-server

   
